version: "3.3"
services:

  quizdb:
    image: postgres:12
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata

  pgadmin:
    image: dpage/pgadmin4:6.9
    depends_on:
      - quizdb
    env_file:
      - .env
    ports:
      - "5050:80"

  backend:
    build:
      context: ./backend
      dockerfile: backend.dockerfile
    depends_on:
      - quizdb
    env_file:
      - .env
    ports:
      - "7070:7070"
    volumes:
      - "./backend/app:/app"

  locust-master:
    image: locustio/locust
    ports:
     - "8089:8089"
    depends_on:
      - backend
    env_file:
      - .env
    volumes:
      - ./locust/src:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089

  locust-worker:
    image: locustio/locust
    depends_on:
      - locust-master
    env_file:
      - .env
    volumes:
      - ./locust/src:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host locust-master

volumes:
  app-db-data:
